name: example

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build image & save artifact
        run: |
          docker build -t test_image:latest -<<EOF
          FROM busybox
          RUN touch abc.txt
          EOF
          docker save test_image:latest -o ./docker.tar

      - uses: actions/upload-artifact@v3
        with:
          name: sprint-name.tar
          path: ./docker.tar
          if-no-files-found: error
